name: notebooks-backend

services:
  notebooks:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTEBOOKS_DB_USER}:${NOTEBOOKS_DB_PASSWORD}@notebooks-db/${NOTEBOOKS_DB_NAME}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    networks:
      - notebooks-net
    depends_on:
      - notebooks-db

  notebooks-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - notebooks-data:/data/db
      - ./db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - notebooks-net

volumes:
  notebooks-data:

networks:
  notebooks-net: